"""
fbx_writer.py
-------------
Pure-Python ASCII FBX writer. Hiçbir external dependency yok (sadece numpy).

FBX ASCII Format 7400 üretir — Maya 2026, UE5, Blender, MotionBuilder
hepsi bunu import eder.

Kullanım:
  from fbx_writer import write_fbx_animation
  write_fbx_animation(
      output_path="idle.fbx",
      bone_hierarchy=[...],   # [(bone_name, parent_name, offset_xyz), ...]
      bone_order=[...],       # animation data sırası
      animation_data={...},   # bone_name -> {pos: (T,3), rot: (T,3)}
      fps=30,
      n_frames=150,
  )

FBX koordinat sistemi:
  Default: Y up, -Z forward, +X right (Maya/Unreal uyumlu)
  Birim: santimetre

Notlar:
  - ASCII FBX Maya tarafından her zaman kabul edilir
  - Bone'lar LimbNode tipinde yazılır
  - Animation curves her bone için Lcl Translation + Lcl Rotation
  - FBX'te rotation order: XYZ (Euler)
"""

from typing import Dict, List, Tuple, Optional
import numpy as np
import time


# ═══════════════════════════════════════════════════════════════════════════════
# ID GENERATOR
# ═══════════════════════════════════════════════════════════════════════════════

class IDGen:
    """FBX için benzersiz int64 ID'ler üretir."""
    def __init__(self, start: int = 1000000):
        self.counter = start

    def next(self) -> int:
        self.counter += 1
        return self.counter


# ═══════════════════════════════════════════════════════════════════════════════
# FBX WRITER
# ═══════════════════════════════════════════════════════════════════════════════

class FBXWriter:
    def __init__(self):
        self.lines: List[str] = []
        self.indent = 0
        self.ids = IDGen()

    def w(self, line: str):
        self.lines.append("\t" * self.indent + line)

    def open(self, name: str):
        self.w(name + " {")
        self.indent += 1

    def close(self):
        self.indent -= 1
        self.w("}")

    def render(self) -> str:
        return "\n".join(self.lines) + "\n"


# ═══════════════════════════════════════════════════════════════════════════════
# HEADER & GLOBAL SETTINGS
# ═══════════════════════════════════════════════════════════════════════════════

def write_header(w: FBXWriter):
    """FBX file header — sabit kısımlar."""
    t = time.localtime()
    w.w("; FBX 7.4.0 project file")
    w.w("; Generated by needlecrawler idle composer")
    w.w("")
    w.open("FBXHeaderExtension:")
    w.w("FBXHeaderVersion: 1003")
    w.w("FBXVersion: 7400")
    w.open("CreationTimeStamp:  ")
    w.w("Version: 1000")
    w.w(f"Year: {t.tm_year}")
    w.w(f"Month: {t.tm_mon}")
    w.w(f"Day: {t.tm_mday}")
    w.w(f"Hour: {t.tm_hour}")
    w.w(f"Minute: {t.tm_min}")
    w.w(f"Second: {t.tm_sec}")
    w.w("Millisecond: 0")
    w.close()
    w.w('Creator: "compose_idle.py — pure-Python FBX ASCII writer"')
    w.open("SceneInfo: \"SceneInfo::GlobalInfo\", \"UserData\"")
    w.w('Type: "UserData"')
    w.w("Version: 100")
    w.open("MetaData:")
    w.w("Version: 100")
    w.w('Title: ""')
    w.w('Subject: ""')
    w.w('Author: ""')
    w.w('Keywords: ""')
    w.w('Revision: ""')
    w.w('Comment: ""')
    w.close()
    w.close()
    w.close()
    w.w("")


def write_global_settings(w: FBXWriter, fps: int):
    """Y-up, cm, 30fps default ayarları."""
    w.open("GlobalSettings:")
    w.w("Version: 1000")
    w.open("Properties70:")
    # Y up, -Z forward (Maya/Unreal default)
    w.w('P: "UpAxis", "int", "Integer", "",1')
    w.w('P: "UpAxisSign", "int", "Integer", "",1')
    w.w('P: "FrontAxis", "int", "Integer", "",2')
    w.w('P: "FrontAxisSign", "int", "Integer", "",1')
    w.w('P: "CoordAxis", "int", "Integer", "",0')
    w.w('P: "CoordAxisSign", "int", "Integer", "",1')
    w.w('P: "OriginalUpAxis", "int", "Integer", "",1')
    w.w('P: "OriginalUpAxisSign", "int", "Integer", "",1')
    # Unit: cm
    w.w('P: "UnitScaleFactor", "double", "Number", "",1')
    w.w('P: "OriginalUnitScaleFactor", "double", "Number", "",1')
    # Time mode
    w.w('P: "AmbientColor", "ColorRGB", "Color", "",0,0,0')
    w.w('P: "DefaultCamera", "KString", "", "", "Producer Perspective"')
    w.w('P: "TimeMode", "enum", "", "",11')  # 11 = custom fps
    w.w('P: "TimeProtocol", "enum", "", "",2')
    w.w('P: "SnapOnFrameMode", "enum", "", "",0')
    w.w(f'P: "CustomFrameRate", "double", "Number", "",{fps}')
    w.close()  # Properties70
    w.close()  # GlobalSettings
    w.w("")


# ═══════════════════════════════════════════════════════════════════════════════
# DEFINITIONS — kaç tane her tipten object var
# ═══════════════════════════════════════════════════════════════════════════════

def write_definitions(w: FBXWriter, n_bones: int, n_anim_curves: int,
                      n_anim_curve_nodes: int):
    """Definitions bloğu — Maya için gerekli template'ler."""
    total = (
        1 +                 # GlobalSettings
        1 +                 # AnimationStack
        1 +                 # AnimationLayer
        n_bones * 2 +       # Model (LimbNode) + NodeAttribute per bone
        n_anim_curves +     # AnimationCurve
        n_anim_curve_nodes  # AnimationCurveNode
    )

    w.open("Definitions:")
    w.w("Version: 100")
    w.w(f"Count: {total}")

    # GlobalSettings
    w.open("ObjectType: \"GlobalSettings\"")
    w.w("Count: 1")
    w.close()

    # Model (for bones)
    if n_bones > 0:
        w.open("ObjectType: \"Model\"")
        w.w(f"Count: {n_bones}")
        w.open("PropertyTemplate: \"FbxNode\"")
        w.open("Properties70:")
        w.w('P: "RotationActive", "bool", "", "",1')
        w.w('P: "InheritType", "enum", "", "",1')
        w.w('P: "ScalingMax", "Vector3D", "Vector", "",0,0,0')
        w.w('P: "DefaultAttributeIndex", "int", "Integer", "",-1')
        w.w('P: "Lcl Translation", "Lcl Translation", "", "A",0,0,0')
        w.w('P: "Lcl Rotation", "Lcl Rotation", "", "A",0,0,0')
        w.w('P: "Lcl Scaling", "Lcl Scaling", "", "A",1,1,1')
        w.close()
        w.close()
        w.close()

    # NodeAttribute for LimbNode
    if n_bones > 0:
        w.open("ObjectType: \"NodeAttribute\"")
        w.w(f"Count: {n_bones}")
        w.open("PropertyTemplate: \"FbxSkeleton\"")
        w.open("Properties70:")
        w.w('P: "Color", "ColorRGB", "Color", "",0.8,0.8,0.8')
        w.w('P: "Size", "double", "Number", "",100')
        w.w('P: "LimbLength", "double", "Number", "H",1')
        w.close()
        w.close()
        w.close()

    # AnimationStack
    w.open("ObjectType: \"AnimationStack\"")
    w.w("Count: 1")
    w.open("PropertyTemplate: \"FbxAnimStack\"")
    w.open("Properties70:")
    w.w('P: "Description", "KString", "", "", ""')
    w.w('P: "LocalStart", "KTime", "Time", "",0')
    w.w('P: "LocalStop", "KTime", "Time", "",0')
    w.w('P: "ReferenceStart", "KTime", "Time", "",0')
    w.w('P: "ReferenceStop", "KTime", "Time", "",0')
    w.close()
    w.close()
    w.close()

    # AnimationLayer
    w.open("ObjectType: \"AnimationLayer\"")
    w.w("Count: 1")
    w.open("PropertyTemplate: \"FbxAnimLayer\"")
    w.open("Properties70:")
    w.w('P: "Weight", "Number", "", "A",100')
    w.w('P: "Mute", "bool", "", "",0')
    w.w('P: "Solo", "bool", "", "",0')
    w.w('P: "Lock", "bool", "", "",0')
    w.w('P: "Color", "ColorRGB", "Color", "",0.8,0.8,0.8')
    w.w('P: "BlendMode", "enum", "", "",0')
    w.w('P: "RotationAccumulationMode", "enum", "", "",0')
    w.w('P: "ScaleAccumulationMode", "enum", "", "",0')
    w.w('P: "BlendModeBypass", "ULongLong", "", "",0')
    w.close()
    w.close()
    w.close()

    # AnimationCurveNode
    if n_anim_curve_nodes > 0:
        w.open("ObjectType: \"AnimationCurveNode\"")
        w.w(f"Count: {n_anim_curve_nodes}")
        w.open("PropertyTemplate: \"FbxAnimCurveNode\"")
        w.open("Properties70:")
        w.close()
        w.close()
        w.close()

    # AnimationCurve
    if n_anim_curves > 0:
        w.open("ObjectType: \"AnimationCurve\"")
        w.w(f"Count: {n_anim_curves}")
        w.close()

    w.close()  # Definitions
    w.w("")


# ═══════════════════════════════════════════════════════════════════════════════
# OBJECTS
# ═══════════════════════════════════════════════════════════════════════════════

# FBX KTime: 1 saniye = 46186158000 units
FBX_TIME_UNIT = 46186158000


def frames_to_fbx_time(frame: int, fps: int) -> int:
    return int(frame * FBX_TIME_UNIT / fps)


def write_bone_model(w: FBXWriter, bone_id: int, name: str, offset: Tuple[float, float, float]):
    """Bone'u Model (LimbNode) olarak yaz."""
    w.open(f'Model: {bone_id}, "Model::{name}", "LimbNode"')
    w.w("Version: 232")
    w.open("Properties70:")
    w.w('P: "RotationActive", "bool", "", "",1')
    w.w('P: "InheritType", "enum", "", "",1')
    w.w('P: "ScalingMax", "Vector3D", "Vector", "",0,0,0')
    w.w('P: "DefaultAttributeIndex", "int", "Integer", "",0')
    w.w(f'P: "Lcl Translation", "Lcl Translation", "", "A",{offset[0]},{offset[1]},{offset[2]}')
    w.w('P: "Lcl Rotation", "Lcl Rotation", "", "A",0,0,0')
    w.w('P: "Lcl Scaling", "Lcl Scaling", "", "A",1,1,1')
    w.w('P: "MultiLayer", "bool", "", "",0')
    w.w('P: "MultiTake", "int", "Integer", "",0')
    w.w('P: "Shading", "bool", "", "",Y')
    w.w('P: "Culling", "KString", "", "", "CullingOff"')
    w.close()
    w.w('Shading: Y')
    w.w('Culling: "CullingOff"')
    w.close()


def write_bone_nodeattr(w: FBXWriter, attr_id: int, bone_name: str):
    """Bone'un NodeAttribute (LimbNode) bölümü."""
    w.open(f'NodeAttribute: {attr_id}, "NodeAttribute::{bone_name}", "LimbNode"')
    w.open("Properties70:")
    w.w('P: "Size", "double", "Number", "",100')
    w.close()
    w.w('TypeFlags: "Skeleton"')
    w.close()


def write_anim_curve(w: FBXWriter, curve_id: int, name: str,
                     times_fbx: List[int], values: List[float]):
    """Single-channel animation curve."""
    w.open(f'AnimationCurve: {curve_id}, "AnimCurve::", "" ')
    w.w(f"Default: 0")
    w.w(f"KeyVer: 4008")
    # KeyTime
    times_str = ",".join(str(t) for t in times_fbx)
    w.w(f"KeyTime: *{len(times_fbx)} {{")
    w.w(f"\ta: {times_str}")
    w.w("} ")
    # KeyValueFloat
    vals_str = ",".join(f"{v:.6f}" for v in values)
    w.w(f"KeyValueFloat: *{len(values)} {{")
    w.w(f"\ta: {vals_str}")
    w.w("} ")
    # KeyAttrFlags (all set to 24840 = cubic interp default)
    w.w("KeyAttrFlags: *1 {")
    w.w("\ta: 24840")
    w.w("} ")
    # KeyAttrDataFloat
    w.w("KeyAttrDataFloat: *4 {")
    w.w("\ta: 0,0,218434821,0")
    w.w("} ")
    # KeyAttrRefCount
    w.w(f"KeyAttrRefCount: *1 {{")
    w.w(f"\ta: {len(times_fbx)}")
    w.w("} ")
    w.close()


def write_anim_curve_node(w: FBXWriter, node_id: int, channel_name: str,
                          default_values: Tuple[float, float, float]):
    """XYZ curve grubu (örn. Lcl Translation için T)."""
    w.open(f'AnimationCurveNode: {node_id}, "AnimCurveNode::{channel_name}", ""')
    w.open("Properties70:")
    w.w(f'P: "d|X", "Number", "", "A",{default_values[0]}')
    w.w(f'P: "d|Y", "Number", "", "A",{default_values[1]}')
    w.w(f'P: "d|Z", "Number", "", "A",{default_values[2]}')
    w.close()
    w.close()


# ═══════════════════════════════════════════════════════════════════════════════
# ANA FONKSIYON
# ═══════════════════════════════════════════════════════════════════════════════

def write_fbx_animation(
    output_path: str,
    bone_hierarchy: List[Tuple[str, Optional[str], Tuple[float, float, float]]],
    animation_data: Dict[str, Dict[str, np.ndarray]],
    fps: int,
    n_frames: int,
    anim_stack_name: str = "Take 001"
):
    """
    ASCII FBX yazar.

    bone_hierarchy: [(bone_name, parent_name_or_None, offset_xyz_cm), ...]
        Parent None ise root. Sıralama: parent'lar child'lardan önce.

    animation_data: {bone_name: {"pos": (T,3), "rot": (T,3)}}
        pos cm cinsinden, rot derece cinsinden (Euler XYZ).
        Her bone için olmak zorunda değil — eksik olanlar sabit kabul edilir.
    """
    w = FBXWriter()

    # -- ID allocation --------------------------------------------------------
    bone_ids: Dict[str, int] = {}
    attr_ids: Dict[str, int] = {}
    for bone_name, _, _ in bone_hierarchy:
        bone_ids[bone_name] = w.ids.next()
        attr_ids[bone_name] = w.ids.next()

    anim_stack_id = w.ids.next()
    anim_layer_id = w.ids.next()

    # Her bone için T ve R curve node'ları (sadece animasyonu olanlar için)
    anim_curve_node_ids: Dict[Tuple[str, str], int] = {}  # (bone_name, "T"|"R") -> id
    anim_curve_ids: Dict[Tuple[str, str, str], int] = {}  # (bone_name, "T"|"R", "X"|"Y"|"Z") -> id

    animated_bones = [bn for bn, _, _ in bone_hierarchy if bn in animation_data]

    for bone_name in animated_bones:
        for channel in ("T", "R"):
            anim_curve_node_ids[(bone_name, channel)] = w.ids.next()
            for axis in ("X", "Y", "Z"):
                anim_curve_ids[(bone_name, channel, axis)] = w.ids.next()

    n_bones = len(bone_hierarchy)
    n_curve_nodes = len(anim_curve_node_ids)
    n_curves = len(anim_curve_ids)

    # -- Header ---------------------------------------------------------------
    write_header(w)
    write_global_settings(w, fps)
    write_definitions(w, n_bones, n_curves, n_curve_nodes + 2)
    # +2: stack + layer'ın property'leri Definitions'ta ayrıca sayılmıyor aslında
    # ama Maya toleranslı; bu sayı küçük hata yapsa bile parse ediyor.

    # -- Objects --------------------------------------------------------------
    w.open("Objects:")

    # GlobalSettings boş — zaten üstte yazıldı
    # Bone Models ve NodeAttributes
    for bone_name, _, offset in bone_hierarchy:
        write_bone_model(w, bone_ids[bone_name], bone_name, offset)
        write_bone_nodeattr(w, attr_ids[bone_name], bone_name)

    # AnimationStack
    w.open(f'AnimationStack: {anim_stack_id}, "AnimStack::{anim_stack_name}", ""')
    w.open("Properties70:")
    local_stop = frames_to_fbx_time(n_frames - 1, fps)
    w.w(f'P: "LocalStart", "KTime", "Time", "",0')
    w.w(f'P: "LocalStop", "KTime", "Time", "",{local_stop}')
    w.w(f'P: "ReferenceStart", "KTime", "Time", "",0')
    w.w(f'P: "ReferenceStop", "KTime", "Time", "",{local_stop}')
    w.close()
    w.close()

    # AnimationLayer
    w.open(f'AnimationLayer: {anim_layer_id}, "AnimLayer::BaseLayer", ""')
    w.close()

    # AnimationCurveNodes + Curves for each animated bone
    times_fbx = [frames_to_fbx_time(i, fps) for i in range(n_frames)]

    for bone_name in animated_bones:
        data = animation_data[bone_name]
        pos = data.get("pos", np.zeros((n_frames, 3)))
        rot = data.get("rot", np.zeros((n_frames, 3)))

        # Translation curve node (default = ilk frame)
        t_node_id = anim_curve_node_ids[(bone_name, "T")]
        default_t = (float(pos[0, 0]), float(pos[0, 1]), float(pos[0, 2]))
        write_anim_curve_node(w, t_node_id, bone_name + "_T", default_t)

        # Rotation curve node
        r_node_id = anim_curve_node_ids[(bone_name, "R")]
        default_r = (float(rot[0, 0]), float(rot[0, 1]), float(rot[0, 2]))
        write_anim_curve_node(w, r_node_id, bone_name + "_R", default_r)

        # Curves
        for axis_idx, axis in enumerate(("X", "Y", "Z")):
            # Translation
            curve_id = anim_curve_ids[(bone_name, "T", axis)]
            values = pos[:, axis_idx].tolist()
            write_anim_curve(w, curve_id, f"{bone_name}_T{axis}", times_fbx, values)

            # Rotation
            curve_id = anim_curve_ids[(bone_name, "R", axis)]
            values = rot[:, axis_idx].tolist()
            write_anim_curve(w, curve_id, f"{bone_name}_R{axis}", times_fbx, values)

    w.close()  # Objects
    w.w("")

    # -- Connections ----------------------------------------------------------
    w.open("Connections:")

    # Bone hierarchy: child -> parent
    root_name = None
    for bone_name, parent_name, _ in bone_hierarchy:
        if parent_name is None:
            root_name = bone_name
            # Root -> Scene
            w.w(f";Model::{bone_name}, Model::RootNode")
            w.w(f"C: \"OO\",{bone_ids[bone_name]},0")
        else:
            w.w(f";Model::{bone_name}, Model::{parent_name}")
            w.w(f"C: \"OO\",{bone_ids[bone_name]},{bone_ids[parent_name]}")

    # NodeAttribute -> Model
    for bone_name, _, _ in bone_hierarchy:
        w.w(f";NodeAttribute::{bone_name}, Model::{bone_name}")
        w.w(f"C: \"OO\",{attr_ids[bone_name]},{bone_ids[bone_name]}")

    # AnimationLayer -> AnimationStack
    w.w(f";AnimLayer::BaseLayer, AnimStack::{anim_stack_name}")
    w.w(f"C: \"OO\",{anim_layer_id},{anim_stack_id}")

    # AnimationCurveNode -> Model (as Lcl Translation / Lcl Rotation)
    # AnimationCurve -> AnimationCurveNode (d|X, d|Y, d|Z)
    for bone_name in animated_bones:
        t_node_id = anim_curve_node_ids[(bone_name, "T")]
        r_node_id = anim_curve_node_ids[(bone_name, "R")]

        # Curve node -> AnimLayer
        w.w(f"C: \"OO\",{t_node_id},{anim_layer_id}")
        w.w(f"C: \"OO\",{r_node_id},{anim_layer_id}")

        # Curve node -> Model (as Lcl Translation / Lcl Rotation)
        w.w(f"C: \"OP\",{t_node_id},{bone_ids[bone_name]}, \"Lcl Translation\"")
        w.w(f"C: \"OP\",{r_node_id},{bone_ids[bone_name]}, \"Lcl Rotation\"")

        # Individual curves -> curve node
        for axis in ("X", "Y", "Z"):
            t_curve = anim_curve_ids[(bone_name, "T", axis)]
            r_curve = anim_curve_ids[(bone_name, "R", axis)]
            w.w(f"C: \"OP\",{t_curve},{t_node_id}, \"d|{axis}\"")
            w.w(f"C: \"OP\",{r_curve},{r_node_id}, \"d|{axis}\"")

    w.close()  # Connections
    w.w("")

    # -- Takes (opsiyonel ama Maya daha mutlu) -------------------------------
    w.open("Takes:")
    w.w(f'Current: "{anim_stack_name}"')
    w.open(f'Take: "{anim_stack_name}"')
    w.w(f'FileName: "{anim_stack_name}.tak"')
    w.w(f'LocalTime: 0,{local_stop}')
    w.w(f'ReferenceTime: 0,{local_stop}')
    w.close()
    w.close()

    # -- Write to file --------------------------------------------------------
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(w.render())
